### ISSUE TITLE
Tuxedomoon

### ISSUE THREAD

**Issue by timchurches** [GuillaumePressiat/stringfix#1]
I liked the Tuxedomoon reference in your blog post about your stringfix package. And I like the idea of the package. I'll try it out and provide feedback (and maybe even some pull requests).

**Comment by GuillaumePressiat** [comment]
Glad to hear that. 
Your participation is welcome.

**Comment by GuillaumePressiat** [comment]
For In a Manner of Speaking, [here](https://www.google.com/search?client=firefox-b-ab&q=nouvelle+vague+in+a+manner+of+speaking) is a cover by Nouvelle Vague.

**Comment by timchurches** [comment]
By strange co-incidence, we were listening to a Nouvelle Vague compilation during dinner last night, and to my surprise there was the Tuxedomoon cover version, which I had completely forgotten about.
